---
ID: "e32266db-5286-536e-bc76-1e8ba55e8724"
Parent: "d92375f5-def7-586c-bd50-8c3c5553479b"
Template: "d92375f5-def7-586c-bd50-8c3c5553479b"
Path: "/sitecore/templates/Project/StyleGuide/Styleguide-FieldUsage-Checkbox/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190620T024501Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
