---
ID: "0c4331b5-6a0f-5f5d-9400-5ad7633035c0"
Parent: "ab8adb8e-48b7-5c97-89f5-3b23695fbb18"
Template: "ab8adb8e-48b7-5c97-89f5-3b23695fbb18"
Path: "/sitecore/templates/Project/StyleGuide/Styleguide-ComponentParams/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190620T024501Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
