---
ID: "a3ff4713-af3b-4faa-a471-4780c19a4dd8"
Parent: "8329758e-32dd-46bb-b1c7-349d8850810d"
Template: "a6868d65-d612-401f-a40a-cd5ba0857b81"
Path: /sitecore/system/Settings/Services/API Keys/Project/StyleGuide/Local
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190618T061300Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
