---
ID: "0da2dc71-9227-5d5d-8f35-9a59d63dc6e9"
Parent: "8254984d-574c-5266-b0bb-2b65143d67cf"
Template: "8254984d-574c-5266-b0bb-2b65143d67cf"
Path: "/sitecore/templates/Project/StyleGuide/Styleguide-FieldUsage-Text/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190620T024503Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
